leftnav:
- identifier: 600855e2-0c52-f75d-6912-2698016f2072
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 5651909e-a209-3ff4-e3ba-e9a8c628205c
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 69f4b17f-a6bd-b15a-f62d-e6f559e9fd54
  name: Projects
  url: /pages/projects
  weight: 30
